#ifndef MUSLIMTIFY_COLORS_H
#define MUSLIMTIFY_COLORS_H

#include "ccompose.h"

#define COLOR_PRIMARY ColorHex(0xFF004F45)
#define COLOR_PRIMARY_ALPHA10 ColorHexA(0xFF004F4526)
#define COLOR_ON_PRIMARY ColorHex(0xFFFFFFFF)

#define COLOR_BACKGROUND ColorHex(0xFFF8FAFA)
#define COLOR_ON_BACKGROUND ColorHex(0xFF191C1D)

#define COLOR_SURFACE ColorHex(0xFF6E7976)
#define COLOR_ON_SURFACE ColorHex(0xFF115E59)

#define COLOR_SURFACE_VARIANT ColorHex(0xFFECFDF5)
#define COLOR_SURFACE_ALT ColorHex(0xFFF2F4F4)

#define COLOR_DISABLED ColorHex(0xFFBEC9C5)
#define COLOR_DISABLED_ALPHA10 ColorHexA(0xFFBEC9C526)

#endif // MUSLIMTIFY_COLORS_H
